services:
  stats-server:
    build:
      context: .
      dockerfile: stat-service/server/Dockerfile
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"  # Порт для доступа с хоста
    environment:
      - SPRING_PROFILES_ACTIVE=default  # Явно указываем профиль
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=Vovs
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - stats-db
    networks:
      - app-net

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: Vovs
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"  # Порт для доступа к БД с хоста
    networks:
      - app-net

  main-service:
    build:
      context: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=postgres  # Исправлено на корректного пользователя
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090  # Используем имя контейнера
    depends_on:
      - main-db
      - stats-server  # Явная зависимость
    networks:
      - app-net
    command: ["sh", "-c", "./wait-for-it.sh stats-server:9090 --timeout=300 --strict -- java -jar /app.jar"]

  main-db:
    image: postgres:13.7-alpine
    container_name: main-db
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6542:5432"  # Порт для доступа к БД с хоста
    networks:
      - app-net

networks:
  app-net:
    driver: bridge