version: '3.8'

services:
  stats-server:
    build:
      context: .
      dockerfile: stat-service/server/Dockerfile
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=Vovs
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      stats-db:
        condition: service_healthy
    networks:
      - app-net
    healthcheck: # Добавлен healthcheck для stats-server
      test: ["CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: Vovs
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Vovs -d stats"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  main-service:
    build:
      context: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090
    depends_on:
      main-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy # Используем healthcheck вместо started
    networks:
      - app-net
    command: ["sh", "-c", "./wait-for-it.sh stats-server:9090 --timeout=120 --strict -- java -jar /app.jar"] # Исправлен адрес

  main-db:
    image: postgres:13.7-alpine
    container_name: main-db
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6542:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d main"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

networks:
  app-net:
    driver: bridge